spring:
  profiles: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MazinIsmail/ConfigServer.git
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'